region                   = "global"
datacenters              = ["nomad-playground-region-dc"]
namespace                = "default"
image                    = "go-worker-demo:latest"
count                    = 5
consul_http_addr         = "http://127.0.0.1:8500"
consul_service_tags      = ["prometheus.enabled=true"]
discovery_service_tags   = []
peer_refresh_interval_ms = "5000"
report_interval_ms       = "4000"
host_volume              = "logs"
