// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: sessionrpc.proto

package sessionrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Action        string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	Payload       string                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	SentAt        string                 `protobuf:"bytes,8,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_sessionrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sessionrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_sessionrpc_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ClientEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientEvent) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientEvent) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClientEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ClientEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ClientEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ClientEvent) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

type GatewayAck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventId           string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SessionId         string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Action            string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Result            string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Message           string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	GatewayId         string                 `protobuf:"bytes,6,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	WorkerId          string                 `protobuf:"bytes,7,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SnapshotObjectKey string                 `protobuf:"bytes,8,opt,name=snapshot_object_key,json=snapshotObjectKey,proto3" json:"snapshot_object_key,omitempty"`
	ProcessedAt       string                 `protobuf:"bytes,9,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GatewayAck) Reset() {
	*x = GatewayAck{}
	mi := &file_sessionrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayAck) ProtoMessage() {}

func (x *GatewayAck) ProtoReflect() protoreflect.Message {
	mi := &file_sessionrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayAck.ProtoReflect.Descriptor instead.
func (*GatewayAck) Descriptor() ([]byte, []int) {
	return file_sessionrpc_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GatewayAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GatewayAck) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GatewayAck) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GatewayAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GatewayAck) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayAck) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *GatewayAck) GetSnapshotObjectKey() string {
	if x != nil {
		return x.SnapshotObjectKey
	}
	return ""
}

func (x *GatewayAck) GetProcessedAt() string {
	if x != nil {
		return x.ProcessedAt
	}
	return ""
}

type SessionEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventId           string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SessionId         string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientId          string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId            uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId          string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Action            string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	Payload           string                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	GatewayId         string                 `protobuf:"bytes,8,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	WorkerId          string                 `protobuf:"bytes,9,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SnapshotObjectKey string                 `protobuf:"bytes,10,opt,name=snapshot_object_key,json=snapshotObjectKey,proto3" json:"snapshot_object_key,omitempty"`
	SentAt            string                 `protobuf:"bytes,11,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ProcessedAt       string                 `protobuf:"bytes,12,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_sessionrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sessionrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_sessionrpc_proto_rawDescGZIP(), []int{2}
}

func (x *SessionEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SessionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEvent) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SessionEvent) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SessionEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SessionEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SessionEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SessionEvent) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *SessionEvent) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *SessionEvent) GetSnapshotObjectKey() string {
	if x != nil {
		return x.SnapshotObjectKey
	}
	return ""
}

func (x *SessionEvent) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *SessionEvent) GetProcessedAt() string {
	if x != nil {
		return x.ProcessedAt
	}
	return ""
}

type SessionResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EventId            string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SessionId          string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Action             string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Result             string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Message            string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	GatewayId          string                 `protobuf:"bytes,6,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	WorkerId           string                 `protobuf:"bytes,7,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SnapshotObjectKey  string                 `protobuf:"bytes,8,opt,name=snapshot_object_key,json=snapshotObjectKey,proto3" json:"snapshot_object_key,omitempty"`
	QueueDepth         int64                  `protobuf:"varint,9,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	ActiveJobs         int64                  `protobuf:"varint,10,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	TemperatureCelsius float64                `protobuf:"fixed64,11,opt,name=temperature_celsius,json=temperatureCelsius,proto3" json:"temperature_celsius,omitempty"`
	ProcessedAt        string                 `protobuf:"bytes,12,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SessionResult) Reset() {
	*x = SessionResult{}
	mi := &file_sessionrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResult) ProtoMessage() {}

func (x *SessionResult) ProtoReflect() protoreflect.Message {
	mi := &file_sessionrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResult.ProtoReflect.Descriptor instead.
func (*SessionResult) Descriptor() ([]byte, []int) {
	return file_sessionrpc_proto_rawDescGZIP(), []int{3}
}

func (x *SessionResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SessionResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionResult) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SessionResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *SessionResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SessionResult) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *SessionResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *SessionResult) GetSnapshotObjectKey() string {
	if x != nil {
		return x.SnapshotObjectKey
	}
	return ""
}

func (x *SessionResult) GetQueueDepth() int64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *SessionResult) GetActiveJobs() int64 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *SessionResult) GetTemperatureCelsius() float64 {
	if x != nil {
		return x.TemperatureCelsius
	}
	return 0
}

func (x *SessionResult) GetProcessedAt() string {
	if x != nil {
		return x.ProcessedAt
	}
	return ""
}

type WorkerStatusReport struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkerId           string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	GatewayId          string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	QueueDepth         int64                  `protobuf:"varint,3,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	ActiveJobs         int64                  `protobuf:"varint,4,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	TemperatureCelsius float64                `protobuf:"fixed64,5,opt,name=temperature_celsius,json=temperatureCelsius,proto3" json:"temperature_celsius,omitempty"`
	OnlineSessions     int64                  `protobuf:"varint,6,opt,name=online_sessions,json=onlineSessions,proto3" json:"online_sessions,omitempty"`
	Message            string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	SentAt             string                 `protobuf:"bytes,8,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkerStatusReport) Reset() {
	*x = WorkerStatusReport{}
	mi := &file_sessionrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatusReport) ProtoMessage() {}

func (x *WorkerStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_sessionrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatusReport.ProtoReflect.Descriptor instead.
func (*WorkerStatusReport) Descriptor() ([]byte, []int) {
	return file_sessionrpc_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerStatusReport) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerStatusReport) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *WorkerStatusReport) GetQueueDepth() int64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *WorkerStatusReport) GetActiveJobs() int64 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *WorkerStatusReport) GetTemperatureCelsius() float64 {
	if x != nil {
		return x.TemperatureCelsius
	}
	return 0
}

func (x *WorkerStatusReport) GetOnlineSessions() int64 {
	if x != nil {
		return x.OnlineSessions
	}
	return 0
}

func (x *WorkerStatusReport) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkerStatusReport) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

type WorkerStatusAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ReportedAt    string                 `protobuf:"bytes,3,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatusAck) Reset() {
	*x = WorkerStatusAck{}
	mi := &file_sessionrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatusAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatusAck) ProtoMessage() {}

func (x *WorkerStatusAck) ProtoReflect() protoreflect.Message {
	mi := &file_sessionrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatusAck.ProtoReflect.Descriptor instead.
func (*WorkerStatusAck) Descriptor() ([]byte, []int) {
	return file_sessionrpc_proto_rawDescGZIP(), []int{5}
}

func (x *WorkerStatusAck) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *WorkerStatusAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkerStatusAck) GetReportedAt() string {
	if x != nil {
		return x.ReportedAt
	}
	return ""
}

type GatewayPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayPingRequest) Reset() {
	*x = GatewayPingRequest{}
	mi := &file_sessionrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayPingRequest) ProtoMessage() {}

func (x *GatewayPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayPingRequest.ProtoReflect.Descriptor instead.
func (*GatewayPingRequest) Descriptor() ([]byte, []int) {
	return file_sessionrpc_proto_rawDescGZIP(), []int{6}
}

func (x *GatewayPingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GatewayPingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	GatewayId     string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	ProcessedAt   string                 `protobuf:"bytes,3,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayPingReply) Reset() {
	*x = GatewayPingReply{}
	mi := &file_sessionrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayPingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayPingReply) ProtoMessage() {}

func (x *GatewayPingReply) ProtoReflect() protoreflect.Message {
	mi := &file_sessionrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayPingReply.ProtoReflect.Descriptor instead.
func (*GatewayPingReply) Descriptor() ([]byte, []int) {
	return file_sessionrpc_proto_rawDescGZIP(), []int{7}
}

func (x *GatewayPingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GatewayPingReply) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayPingReply) GetProcessedAt() string {
	if x != nil {
		return x.ProcessedAt
	}
	return ""
}

var File_sessionrpc_proto protoreflect.FileDescriptor

const file_sessionrpc_proto_rawDesc = "" +
	"\n" +
	"\x10sessionrpc.proto\x12\n" +
	"sessionrpc\"\xe5\x01\n" +
	"\vClientEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\a \x01(\tR\apayload\x12\x17\n" +
	"\asent_at\x18\b \x01(\tR\x06sentAt\"\x9f\x02\n" +
	"\n" +
	"GatewayAck\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x06 \x01(\tR\tgatewayId\x12\x1b\n" +
	"\tworker_id\x18\a \x01(\tR\bworkerId\x12.\n" +
	"\x13snapshot_object_key\x18\b \x01(\tR\x11snapshotObjectKey\x12!\n" +
	"\fprocessed_at\x18\t \x01(\tR\vprocessedAt\"\xf5\x02\n" +
	"\fSessionEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\a \x01(\tR\apayload\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\b \x01(\tR\tgatewayId\x12\x1b\n" +
	"\tworker_id\x18\t \x01(\tR\bworkerId\x12.\n" +
	"\x13snapshot_object_key\x18\n" +
	" \x01(\tR\x11snapshotObjectKey\x12\x17\n" +
	"\asent_at\x18\v \x01(\tR\x06sentAt\x12!\n" +
	"\fprocessed_at\x18\f \x01(\tR\vprocessedAt\"\x95\x03\n" +
	"\rSessionResult\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x06 \x01(\tR\tgatewayId\x12\x1b\n" +
	"\tworker_id\x18\a \x01(\tR\bworkerId\x12.\n" +
	"\x13snapshot_object_key\x18\b \x01(\tR\x11snapshotObjectKey\x12\x1f\n" +
	"\vqueue_depth\x18\t \x01(\x03R\n" +
	"queueDepth\x12\x1f\n" +
	"\vactive_jobs\x18\n" +
	" \x01(\x03R\n" +
	"activeJobs\x12/\n" +
	"\x13temperature_celsius\x18\v \x01(\x01R\x12temperatureCelsius\x12!\n" +
	"\fprocessed_at\x18\f \x01(\tR\vprocessedAt\"\x9f\x02\n" +
	"\x12WorkerStatusReport\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\x12\x1f\n" +
	"\vqueue_depth\x18\x03 \x01(\x03R\n" +
	"queueDepth\x12\x1f\n" +
	"\vactive_jobs\x18\x04 \x01(\x03R\n" +
	"activeJobs\x12/\n" +
	"\x13temperature_celsius\x18\x05 \x01(\x01R\x12temperatureCelsius\x12'\n" +
	"\x0fonline_sessions\x18\x06 \x01(\x03R\x0eonlineSessions\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x17\n" +
	"\asent_at\x18\b \x01(\tR\x06sentAt\"d\n" +
	"\x0fWorkerStatusAck\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vreported_at\x18\x03 \x01(\tR\n" +
	"reportedAt\".\n" +
	"\x12GatewayPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"n\n" +
	"\x10GatewayPingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\x12!\n" +
	"\fprocessed_at\x18\x03 \x01(\tR\vprocessedAt2\xf1\x01\n" +
	"\x0eGatewayService\x12B\n" +
	"\vOpenSession\x12\x17.sessionrpc.ClientEvent\x1a\x16.sessionrpc.GatewayAck(\x010\x01\x12Q\n" +
	"\x12ReportWorkerStatus\x12\x1e.sessionrpc.WorkerStatusReport\x1a\x1b.sessionrpc.WorkerStatusAck\x12H\n" +
	"\bPingText\x12\x1e.sessionrpc.GatewayPingRequest\x1a\x1c.sessionrpc.GatewayPingReply2[\n" +
	"\rWorkerService\x12J\n" +
	"\x13ProcessSessionEvent\x12\x18.sessionrpc.SessionEvent\x1a\x19.sessionrpc.SessionResultB;Z9github.com/jianli/zhishichubei/tool/sessionrpc;sessionrpcb\x06proto3"

var (
	file_sessionrpc_proto_rawDescOnce sync.Once
	file_sessionrpc_proto_rawDescData []byte
)

func file_sessionrpc_proto_rawDescGZIP() []byte {
	file_sessionrpc_proto_rawDescOnce.Do(func() {
		file_sessionrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sessionrpc_proto_rawDesc), len(file_sessionrpc_proto_rawDesc)))
	})
	return file_sessionrpc_proto_rawDescData
}

var file_sessionrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sessionrpc_proto_goTypes = []any{
	(*ClientEvent)(nil),        // 0: sessionrpc.ClientEvent
	(*GatewayAck)(nil),         // 1: sessionrpc.GatewayAck
	(*SessionEvent)(nil),       // 2: sessionrpc.SessionEvent
	(*SessionResult)(nil),      // 3: sessionrpc.SessionResult
	(*WorkerStatusReport)(nil), // 4: sessionrpc.WorkerStatusReport
	(*WorkerStatusAck)(nil),    // 5: sessionrpc.WorkerStatusAck
	(*GatewayPingRequest)(nil), // 6: sessionrpc.GatewayPingRequest
	(*GatewayPingReply)(nil),   // 7: sessionrpc.GatewayPingReply
}
var file_sessionrpc_proto_depIdxs = []int32{
	0, // 0: sessionrpc.GatewayService.OpenSession:input_type -> sessionrpc.ClientEvent
	4, // 1: sessionrpc.GatewayService.ReportWorkerStatus:input_type -> sessionrpc.WorkerStatusReport
	6, // 2: sessionrpc.GatewayService.PingText:input_type -> sessionrpc.GatewayPingRequest
	2, // 3: sessionrpc.WorkerService.ProcessSessionEvent:input_type -> sessionrpc.SessionEvent
	1, // 4: sessionrpc.GatewayService.OpenSession:output_type -> sessionrpc.GatewayAck
	5, // 5: sessionrpc.GatewayService.ReportWorkerStatus:output_type -> sessionrpc.WorkerStatusAck
	7, // 6: sessionrpc.GatewayService.PingText:output_type -> sessionrpc.GatewayPingReply
	3, // 7: sessionrpc.WorkerService.ProcessSessionEvent:output_type -> sessionrpc.SessionResult
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sessionrpc_proto_init() }
func file_sessionrpc_proto_init() {
	if File_sessionrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sessionrpc_proto_rawDesc), len(file_sessionrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_sessionrpc_proto_goTypes,
		DependencyIndexes: file_sessionrpc_proto_depIdxs,
		MessageInfos:      file_sessionrpc_proto_msgTypes,
	}.Build()
	File_sessionrpc_proto = out.File
	file_sessionrpc_proto_goTypes = nil
	file_sessionrpc_proto_depIdxs = nil
}
